# Generated by Django 4.1.7 on 2023-03-12 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer2',
            new_name='answer_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer3',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer4',
            new_name='answer_4',
        ),
    ]
