# Generated by Django 4.1.7 on 2023-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0004_question_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='question_counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='actual_question',
            field=models.IntegerField(help_text='id of actual question'),
        ),
        migrations.AlterField(
            model_name='game',
            name='question_quantity',
            field=models.IntegerField(help_text='value specified by user, how many question are in this game'),
        ),
    ]
