# Generated by Django 4.1.7 on 2023-03-25 21:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0005_game_question_counter_alter_game_actual_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='question_counter',
            field=models.IntegerField(default=1, help_text='counts number of questions answered in this game'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.99), django.core.validators.MaxValueValidator(4.01)]),
        ),
    ]
