# Generated by Django 4.1.7 on 2023-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0007_game_questions_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='nickname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
