# Generated by Django 4.1.7 on 2023-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0008_game_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='percentage',
            field=models.FloatField(null=True),
        ),
    ]
