# Generated by Django 4.1.7 on 2023-05-26 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0011_game_completed_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='age',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0.99), django.core.validators.MaxValueValidator(150)]),
        ),
    ]
