# Generated by Django 4.1.7 on 2023-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_django_app', '0012_game_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
